- name: Install Jenkins on Amazon Linux EC2
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
      register: update_result

    - name: Install Java
      command: amazon-linux-extras install java-openjdk11 -y

    - name: Add Jenkins repository key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        enabled: yes
        gpgcheck: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Start and enable Jenkins service
      service: name=jenkins state=started
